/**
 * "Open the application" — literally. Builds a double-clickable
 * /Applications/Context Autopilot.app that (1) starts the observer daemon if
 * it isn't running and (2) brings up the menu bar icon. No terminal in the
 * loop after the first install.
 *
 * The bundle's executable is a tiny launcher script with the absolute paths
 * to the current node binary and this CLI baked in (GUI apps get a minimal
 * PATH, so "node" alone would not resolve). The same daemon-start script is
 * written to ~/.ctxlayer/bin/start-observer.sh so the menu bar app can revive
 * a dead daemon too.
 */

import { spawnSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ctxlayerHome, ambientRoot } from './config.js';
import { helperBinary } from './helper.js';
import { menubarBinary } from './menubar.js';

export function daemonScriptPath(): string {
  return join(ctxlayerHome(), 'bin', 'start-observer.sh');
}

/**
 * Write the daemon-start script: launches `observe --agent` detached unless a
 * fresh heartbeat says one is already running. Idempotent and safe to re-run.
 */
export function writeDaemonScript(cliPath: string): string {
  const path = daemonScriptPath();
  mkdirSync(join(ctxlayerHome(), 'bin'), { recursive: true });
  const heartbeat = join(ambientRoot(), 'heartbeat');
  const log = join(ambientRoot(), 'daemon.log');
  const script = `#!/bin/sh
# Context Autopilot — start the ambient observer unless one is already alive.
# Generated by ctxlayer; absolute paths baked in for GUI (no-PATH) contexts.
hb="${heartbeat}"
if [ -f "$hb" ]; then
  now=$(date +%s)
  mod=$(stat -f %m "$hb" 2>/dev/null || echo 0)
  if [ $((now - mod)) -lt 12 ]; then
    exit 0
  fi
fi
mkdir -p "${ambientRoot()}"
nohup "${process.execPath}" "${cliPath}" observe --agent >> "${log}" 2>&1 &
`;
  writeFileSync(path, script, 'utf8');
  chmodSync(path, 0o755);
  return path;
}

const APP_NAME = 'Context Autopilot';

/**
 * Render the eye icon and pack an .icns for the bundle. Best-effort: any
 * failure (no helper, no iconutil) just means the app ships icon-less.
 */
function buildIcns(outIcns: string): boolean {
  const helper = helperBinary();
  if (!helper) return false;
  const work = mkdtempSync(join(tmpdir(), 'ctx-icon-'));
  try {
    const master = join(work, 'icon-1024.png');
    if (spawnSync(helper, ['appicon', master], { timeout: 30_000 }).status !== 0) return false;
    const iconset = join(work, 'AppIcon.iconset');
    mkdirSync(iconset);
    // The sizes iconutil expects; @2x variants share the doubled pixel size.
    const sizes: [string, number][] = [
      ['icon_16x16.png', 16], ['icon_16x16@2x.png', 32],
      ['icon_32x32.png', 32], ['icon_32x32@2x.png', 64],
      ['icon_128x128.png', 128], ['icon_128x128@2x.png', 256],
      ['icon_256x256.png', 256], ['icon_256x256@2x.png', 512],
      ['icon_512x512.png', 512], ['icon_512x512@2x.png', 1024],
    ];
    for (const [name, px] of sizes) {
      const res = spawnSync('sips', ['-z', String(px), String(px), master, '--out', join(iconset, name)], {
        stdio: 'ignore',
        timeout: 15_000,
      });
      if (res.status !== 0) return false;
    }
    return spawnSync('iconutil', ['-c', 'icns', iconset, '-o', outIcns], { stdio: 'ignore', timeout: 30_000 }).status === 0;
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

/** Tell LaunchServices about the bundle so Spotlight lists it immediately. */
function registerWithLaunchServices(appPath: string): void {
  const lsregister =
    '/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister';
  if (existsSync(lsregister)) {
    spawnSync(lsregister, ['-f', appPath], { stdio: 'ignore', timeout: 30_000 });
  }
}

export interface AppBuildResult {
  appPath: string;
  created: boolean;
}

/**
 * Build (or refresh) /Applications/Context Autopilot.app. Returns null when
 * the menu bar binary can't be compiled (no swiftc).
 */
export function buildAppBundle(cliPath: string, applicationsDir = '/Applications'): AppBuildResult | null {
  const menubar = menubarBinary();
  if (!menubar) return null;
  const daemonScript = writeDaemonScript(cliPath);

  const appPath = join(applicationsDir, `${APP_NAME}.app`);
  const created = !existsSync(appPath);
  const macos = join(appPath, 'Contents', 'MacOS');
  const resources = join(appPath, 'Contents', 'Resources');
  mkdirSync(macos, { recursive: true });
  mkdirSync(resources, { recursive: true });

  const hasIcon = buildIcns(join(resources, 'AppIcon.icns'));

  // LSUIElement: menu-bar-only — no dock icon, no menu bar takeover.
  writeFileSync(
    join(appPath, 'Contents', 'Info.plist'),
    `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>CFBundleName</key><string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key><string>${APP_NAME}</string>
    <key>CFBundleIdentifier</key><string>ai.thecontextlayer.autopilot</string>
    <key>CFBundleVersion</key><string>0.6.0</string>
    <key>CFBundleShortVersionString</key><string>0.6.0</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleExecutable</key><string>launcher</string>
${hasIcon ? '    <key>CFBundleIconFile</key><string>AppIcon</string>\n' : ''}    <key>LSUIElement</key><true/>
    <key>NSHumanReadableCopyright</key><string>MIT © The Context Layer</string>
  </dict>
</plist>
`,
    'utf8',
  );

  const launcher = join(macos, 'launcher');
  writeFileSync(
    launcher,
    `#!/bin/sh
# Context Autopilot launcher: ensure the observer is running, show the menu bar icon.
"${daemonScript}"
exec "${menubar}"
`,
    'utf8',
  );
  chmodSync(launcher, 0o755);
  // Make Spotlight/Finder aware immediately — a fresh unsigned bundle
  // otherwise may not surface in search until the next index sweep.
  registerWithLaunchServices(appPath);
  return { appPath, created };
}
