/**
 * "Open the application" — literally. Builds a double-clickable
 * /Applications/Context Autopilot.app that (1) starts the observer daemon if
 * it isn't running and (2) brings up the menu bar icon. No terminal in the
 * loop after the first install.
 *
 * The bundle's executable is a tiny launcher script with the absolute paths
 * to the current node binary and this CLI baked in (GUI apps get a minimal
 * PATH, so "node" alone would not resolve). The same daemon-start script is
 * written to ~/.ctxlayer/bin/start-observer.sh so the menu bar app can revive
 * a dead daemon too.
 */

import { chmodSync, existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ctxlayerHome, ambientRoot } from './config.js';
import { menubarBinary } from './menubar.js';

export function daemonScriptPath(): string {
  return join(ctxlayerHome(), 'bin', 'start-observer.sh');
}

/**
 * Write the daemon-start script: launches `observe --agent` detached unless a
 * fresh heartbeat says one is already running. Idempotent and safe to re-run.
 */
export function writeDaemonScript(cliPath: string): string {
  const path = daemonScriptPath();
  mkdirSync(join(ctxlayerHome(), 'bin'), { recursive: true });
  const heartbeat = join(ambientRoot(), 'heartbeat');
  const log = join(ambientRoot(), 'daemon.log');
  const script = `#!/bin/sh
# Context Autopilot — start the ambient observer unless one is already alive.
# Generated by ctxlayer; absolute paths baked in for GUI (no-PATH) contexts.
hb="${heartbeat}"
if [ -f "$hb" ]; then
  now=$(date +%s)
  mod=$(stat -f %m "$hb" 2>/dev/null || echo 0)
  if [ $((now - mod)) -lt 12 ]; then
    exit 0
  fi
fi
mkdir -p "${ambientRoot()}"
nohup "${process.execPath}" "${cliPath}" observe --agent >> "${log}" 2>&1 &
`;
  writeFileSync(path, script, 'utf8');
  chmodSync(path, 0o755);
  return path;
}

const APP_NAME = 'Context Autopilot';

export interface AppBuildResult {
  appPath: string;
  created: boolean;
}

/**
 * Build (or refresh) /Applications/Context Autopilot.app. Returns null when
 * the menu bar binary can't be compiled (no swiftc).
 */
export function buildAppBundle(cliPath: string, applicationsDir = '/Applications'): AppBuildResult | null {
  const menubar = menubarBinary();
  if (!menubar) return null;
  const daemonScript = writeDaemonScript(cliPath);

  const appPath = join(applicationsDir, `${APP_NAME}.app`);
  const created = !existsSync(appPath);
  const macos = join(appPath, 'Contents', 'MacOS');
  mkdirSync(macos, { recursive: true });

  // LSUIElement: menu-bar-only — no dock icon, no menu bar takeover.
  writeFileSync(
    join(appPath, 'Contents', 'Info.plist'),
    `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>CFBundleName</key><string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key><string>${APP_NAME}</string>
    <key>CFBundleIdentifier</key><string>ai.thecontextlayer.autopilot</string>
    <key>CFBundleVersion</key><string>0.6.0</string>
    <key>CFBundleShortVersionString</key><string>0.6.0</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleExecutable</key><string>launcher</string>
    <key>LSUIElement</key><true/>
    <key>NSHumanReadableCopyright</key><string>MIT © The Context Layer</string>
  </dict>
</plist>
`,
    'utf8',
  );

  const launcher = join(macos, 'launcher');
  writeFileSync(
    launcher,
    `#!/bin/sh
# Context Autopilot launcher: ensure the observer is running, show the menu bar icon.
"${daemonScript}"
exec "${menubar}"
`,
    'utf8',
  );
  chmodSync(launcher, 0o755);
  // A stale quarantine/cache bump helps Finder notice the refresh.
  try {
    statSync(appPath);
  } catch {
    // fine
  }
  return { appPath, created };
}
